type: 2d
csv_path: '/share/pi/nigam/projects/zphuo/data/omop_extract_PHI/som-nero-phi-nigam-starr.frazier/cohort_0.2.0_master_file_anon.csv'
sample_frac: 1.0
dicom_dir: /local-scratch/nigam/datasets/PE/inspect/anon_dicoms_tar/
output_dir: /local-scratch/nigam/datasets/PE/inspect/anon_pe_features_full_new


batch_size: 256

transform:
    channels: repeat 
    resize_size: 256
    crop_size: 224
    final_size: 224

