n_gpus: 1
get_features: true 
stage: extract
output_dir: /home/mschuang/radfusion3.0/outputs
test_split: all

exp:
  base_dir: ./outputs
  name: test

trainer:
  weights_summary: top
  seed: 6
  val_check_interval: 1.0
  limit_val_batches: 1.0
  resume_from_checkpoint: null
  precision: 16  # set to 16 for O1 mixed precision, 32 for O0 full precision
  max_steps: 100_000
  gradient_clip_val: 0
  num_workers: 16

defaults:
  - dataset: stanford_16_22
  - model: dinov2
